# Generated by Django 4.1.7 on 2023-02-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=25, verbose_name='Назва компанії')),
                ('culture', models.CharField(max_length=20, verbose_name='Культура')),
                ('price', models.CharField(max_length=230, verbose_name='Ціна')),
                ('date', models.DateTimeField(verbose_name='Дата публікації')),

            ],
        ),
    ]
