# Generated by Django 4.1.7 on 2023-04-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='idUser',
            field=models.CharField(max_length=230, verbose_name='idUser'),
        ),
    ]
