# Generated by Django 4.1.7 on 2023-04-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_alter_artiles_iduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=230, verbose_name='idUser')),
                ('name_company', models.CharField(max_length=25, verbose_name='Назва компанії')),
                ('culture', models.CharField(max_length=20, verbose_name='Культура')),
                ('price', models.CharField(max_length=230, verbose_name='Ціна')),
                ('date', models.DateTimeField(verbose_name='Дата публікації')),
            ],
        ),
        migrations.RemoveField(
            model_name='artiles',
            name='idUser',
        ),
    ]
